### ISSUE TITLE
Web components don't appear on hotjar records

### ISSUE THREAD

**Issue by olkeoguz** [Trendyol/baklava#344]
**Describe the bug**
We are implementing below styles to avoid the FOUCE effect but this causes web components not appearing in hotjar recordings.
```css
/* Prevent FOUCE */
:not(:defined) {
  visibility: hidden;
}
```

**Screenshots**
We have bl-tab-group, bl-button, bl-badge and etc. that don't appear as below.
![image](https://user-images.githubusercontent.com/70342517/209135027-c0fe755c-84e8-4a1a-9508-47c89394d0f8.png)

**Additional context**
We should let the developers deal with this issue and apply these styles in their own applications.
