### ISSUE TITLE
[BUG]: Checkbox whitespace

### ISSUE THREAD

**Issue by AykutSarac** [Trendyol/baklava#682]
### Issue description

Checkbox whitespace is broken for smaller screens

### Media & Screenshots

<img width="261" alt="image" src="https://github.com/Trendyol/baklava/assets/47941171/cc31d0ab-bba2-4adc-8dc1-ea6e36d75070">

### Baklava Version

2.3.0-beta.3

### Operating system

---

### Priority this issue should have

Medium (should be fixed soon)

### Please review the checkboxes that are applicable.

- [ ] This issue is directly related to React

**Comment by fatihhayri** [comment]
checkbox label 

```css
.label {
    word-break: break-all;
}
```

change with:

```css
.label {
    word-break: initial;
}
```

What is the reason for the 'break-all' defination?
