### ISSUE TITLE
[Feature Request]: <Change default color for all components>

### ISSUE THREAD

**Issue by qraxiss** [Trendyol/baklava#722]
### Describe the problem or use case

I need use Baklava different color palettes.

**Comment by 0o001** [comment]
You can customize the color palette as follows.

```css
:root {
  --bl-badge-color: #ccc;
  --bl-primary-color: #000;
}
```

Helpful links;

https://baklava.design/?path=/docs/design-system-colors--documentation
https://baklava.design/?path=/docs/documentation-customizing-baklava-theme--documentation

https://colorhunt.co
