### ISSUE TITLE
Dark Mode Color Palette

### ISSUE THREAD

**Issue by buseselvi** [Trendyol/baklava#770]
Design link: https://www.figma.com/design/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=10654-19509&t=HAjPiyAXGX75uPBN-1

**Comment by mstfymrtc** [comment]
up up up!

**Comment by canberkonem** [comment]
# Dark Mode Support Implementation for Baklava Design System

## Status

Proposed

## Context

Baklava Design System currently uses CSS custom properties for all color definitions in a light mode. Dark mode color values are already defined in the design system but need to be implemented. We need to implement dark mode support across the entire design system while maintaining the existing CSS variable structure.

### Current State

- All colors are defined as CSS variables (e.g., `--bl-color-primary`)
- Components consume these global color tokens
- Only light mode values are currently active in the codebase
- Colors are centrally managed in `default.css`
- Dark mode color values are defined in design system but not implemented

## Decision

Implement dark mode through CSS custom property overrides at the document root level:

### Implementation

```css
/* default.css */

/* Light Theme (Default) */
:root {
    --bl-color-primary: #f27a1a;
    --bl-color-primary-highlight: #ef6114;
    --bl-color-primary-contrast: #fef2e8;
  /* ... other color tokens */
}

/* Dark Theme */
[data-bl-mode="dark"] {
    color-scheme: dark;
    --bl-color-primary: #fb882b;
    --bl-color-primary-highlight: #ed7b16;
    --bl-color-primary-contrast: #1f1d18;
  /* ... other color tokens */
}
```

### Usage

```html
<!-- Enable dark mode -->
<html data-bl-mode="dark">
  <!-- All components will automatically use dark mode colors -->
</html>
```

## Consequences

### Positive

- No changes required to individual components
- Maintains existing CSS variable structure
- Single point of control for mode switching
- Simple implementation as color mappings are predefined

### Negative

- Initial testing required across all components
- Need to add mode selector to global CSS
- Consumers need to implement their own mode management system as there's no built-in mode switcher

### Risks

- Need to verify all color token usage across components

## References

- [Baklava Design Guide](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide)
- [Using CSS custom properties (variables) - MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)
- [CSS Color Scheme - MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme)
